KelimeOyunu/Controllers/WordController.cs
using KelimeOyunu.Helper;
using KelimeOyunu.Models;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace KelimeOyunu.Controllers
{
    public class WordController : Controller
    {
        public ActionResult KelimeEkleme()
        {
            return View();
        }

        [HttpPost]
        public ActionResult KelimeEkle(string KelimeTr, string KelimeEng, int KelimeKonu, HttpPostedFileBase Dosya)
        {
            DapperHelper helper = new DapperHelper();
            int dosyaid = 0;

            if (Dosya != null && Dosya.ContentLength > 0)
            {
                byte[] dosyaDonusturucu;
                using (BinaryReader reader = new BinaryReader(Dosya.InputStream))
                {
                    dosyaDonusturucu = reader.ReadBytes(Dosya.ContentLength);
                }

                string sqldosya = "insert into Fotograf (FotografPath) output inserted.FotografID values (@FotografPath)";
                dosyaid = helper.ExecuteScalar<int>(sqldosya, new
                {
                    FotografPath = dosyaDonusturucu
                });

            }


            string sql = "insert Kelimeler(KelimeTr,KelimeEng,KonuID,FotografID) values (@KelimeTR,@KelimeEng,@KonuID,@FotografID)";
            helper.Execute(sql, new
            {
                KelimeTr = KelimeTr,
                KelimeEng = KelimeEng,
                KonuID = KelimeKonu,
                FotografID = dosyaid
            });


            string kullaniciSayisi= "select count(*) from Kullanicilar";
            int tutucu = helper.ExecuteScalar<int>(kullaniciSayisi);

            for (int i = 1;i<=tutucu;i++) 
            {
                string insertintoToplu = @"insert into SoruSayaci(SoruBilmeSayaci,KelimeID,KullaniciID) values(0,
                                          (select KelimeID from Kelimeler where KelimeEng=@KelimeEng),"+i+")";
                helper.Execute(insertintoToplu, new {KelimeEng=KelimeEng });
                
            }

            return RedirectToAction("KelimeEkleme");
        }

        public ActionResult CumleEkleme()
        {
            DapperHelper helper = new DapperHelper();
            string sql = "select * from Kelimeler";


            return View(helper.Query<KelimeModel>(sql));
        }

        [HttpPost]
        public ActionResult CumleEkleme(int KelimeID,string CumleOrnegi,string secenek1, string secenek2, string secenek3)
        {
            DapperHelper helper = new DapperHelper();

            string sql = @"insert into Sorular(CumleOrnegi,SoruCumlesi,Secenek1,Secenek2,Secenek3,Secenek4,SecenekDogru,KelimeID) 
                             values(@CumleOrnegi,'What does '+ (select LOWER(KelimeENG) from Kelimeler Where KelimeID=@KelimeID)+' mean?'
                            ,@Secenek1,@Secenek2,@Secenek3,(select KelimeTR from Kelimeler where KelimeID=@KelimeID)
                            ,(select KelimeTR from Kelimeler where KelimeID=@KelimeID),@KelimeID)";

            helper.Execute(sql, new { CumleOrnegi = CumleOrnegi, KelimeID = KelimeID,  secenek1 = secenek1, secenek2 = secenek2, secenek3 = secenek3 });

            return RedirectToAction("CumleEkleme");
        }
    }
}

KelimeOyunu/Views/Word/CumleEkleme.cshtml
@model IEnumerable<KelimeOyunu.Models.KelimeModel>
@{
    ViewBag.Title = "CumleEkleme";
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Kelmenin ID'si</th>
            <th scope="col">Kelimenin Türkçesi</th>
            <th scope="col">Kelimenin İngilizcesi</th>
        </tr>
    </thead>
    <tbody>


        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.KelimeID</th>
                <td>@item.KelimeTr</td>
                <td>@item.KelimeEng</td>
                <td>
                    <button id="@item.KelimeID" class="btn btn-success kelime-sec" data-toggle="modal" data-target="#Modal1" data-id="@item.KelimeID">
                        <h5>Cümle Girin</h5>
                    </button>
                </td>
            </tr>
        }

    </tbody>
</table>

<div class="modal" id="Modal1">
    <div class="modal-dialog bg-success">

        <div class="modal-header">
            <h2 class="modal-title">Soru Ekleme Menüsü</h2>
        </div>
        <form action="/word/CumleEkleme" method="post">
            <div class="modal-body">

                <input type="hidden" id="KelimeID" name="KelimeID" />
                <label>Örnek cümlenizi girin:</label>
                <input type="text" id="CumleOrnegi" name="CumleOrnegi" class="text-left" placeholder="Ali playing football with the ball." />
                <br />
                <label>Yanlış seçenekleri giriniz: </label>
                <input type="text" id="secenek1" name="secenek1" class="text-capitalize" placeholder="Çim" />
                <br />
                <input type="text" id="secenek2" name="secenek2" class="text-capitalize" placeholder="Ayakkabı" />
                <br />
                <input type="text" id="secenek3" name="secenek3" class="text-capitalize" placeholder="Kale" />
                <br />
                <button id="gonder" type="submit" class="btn btn-success">Gönder </button>
            </div>
        </form>
    </div>
</div>





<script>
    document.addEventListener("DOMContentLoaded", function () {
        const buttons = document.querySelectorAll('.kelime-sec');
        buttons.forEach(button => {
            button.addEventListener('click', function () {
                const KelimeID = button.getAttribute('data-id');
                document.getElementById('KelimeID').value = KelimeID;
            });
        });
    });
</script>

KelimeOyunu/Views/Word/KelimeEkleme.cshtml
@{
    ViewBag.Title = "KelimeEkleme";
}

<h2>KelimeEkleme</h2>

@using (Html.BeginForm("KelimeEkle", "Word", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-outline mb-4">
        <label class="form-label" for="form3Example3">Kelimeyi Girin:</label>
        <input type="text" id="KelimeTr" name="KelimeTr" class="form-control form-control-lg"
               placeholder="Kelimenin Türkçesini giriniz." />
    </div>
    <br />

    <div class="form-outline mb-4">
        <label class="form-label" for="form3Example3">Kelimenin İngilizcesi:</label>
        <input type="text" id="KelimeEng" name="KelimeEng" class="form-control form-control-lg"
               placeholder="Kelimenin İngilizcesini giriniz." />
    </div>
    <br />
    <div>
        <label for="KelimeKonu">Kelimenin Konusu:</label>
        <select name="KelimeKonu" class="form-select">
            <option selected value="1">Yiyecekler ve İçecekler</option>
            <option value="2">Spor ve Aktiviteler</option>
            <option value="3">Sağlık ve Zindelik</option>
            <option value="4">İş ve Eğitim</option>
            <option value="5">Seyahat ve Kültür</option>
            <option value="6">Ev ve Yaşam</option>
            <option value="7">Teknoloji ve Bilim</option>
            <option value="8">Eğlence ve Sanat</option>
            <option value="9">Doğa ve Çevre</option>
            <option value="10">Hayvanlar</option>
            <option value="11">Aletler ve Makineler</option>
        </select>
    </div>
    <br />


    <input type="file" accept="image/*" id="Dosya" name="Dosya" />
    <br />

    <div class="form-outline mb-4">
        <button type="submit" class="btn btn-primary btn-lg"
                style="padding-left: 2.5rem; padding-right: 2.5rem;">
            Kelime Ekle
        </button>
    </div>
}